project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "SOPQ 2324"
  description: "Web da asignatrua Simulación e Optimización de Procesos Químicos"
  site-url: https://anxosanchez.github.io/SOPQ-2324
  repo-url: https://github.com/anxosanchez/SOPQ-2324
  repo-actions: [edit, issue]
  
  page-footer:
    background: "#D9E3E4" # "#000002"  "#7eb7c2" primary "#D9E3E4"
    left: |
      &copy; Copyright 2023, Anxo Sánchez
    right: |
      Este site está inspirado no site STA 210, deseñado por Mine Çetinkaya-Rundel

  sidebar:
    background: "#D9E3E4" #"#7eb7c2"  # "#D9E3E4" primary
    logo: "imaxes/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/anxosanchez/SOPQ-2324
        text: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/anxo-s%C3%A1nchez-berm%C3%BAdez-79086321/
        text: Linkedin
    menu:
      - text: Foro
        url: https://moovi.uvigo.gal/mod/forum/view.php?id=759112
      - text: Campusremoto 
        url: https://campusremotouvigo.gal/access/public/meeting/682475815
      - text: Moovi
        url: https://moovi.uvigo.gal
    
    style: "docked"
    search: true
    collapse-level: 1

    contents:
      - section: "Información xeral"
        contents:
        - href: course-overview.qmd
          text: "Información da materia" 
        - href: index.qmd
          text: Programación
        - href: course-syllabus.qmd
          text: Guía Docente
        - href: course-team.qmd
          text: Profesorado
        - href: links.qmd
          text: Ligazońs
        - href: course-faq.qmd            
          text: FAQ
      - section: "Computing"
        contents: 
        - href: computing-access.qmd
          text: Access
        - href: computing-troubleshooting.qmd
          text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - section: "Proxecto"
        contents:
        - href: project-description.qmd
          text: Instrucións
        - href: project-tips-resources.qmd
          text: Tips + recusos

        
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [solar, theme-dark.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: false

execute:
  freeze: auto

editor: visual    
    





