---
title: "SOPQ 23-24: Simulaci칩n e Optimizaci칩n de Procesos Qu칤micos"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
#navbar: false
---

# Introduci칩n

Esta p치xina cont칠n un esquema dos temas, contido e tarefas para o semestre.
Ten en conta que este horario actualizarase a medida que avanza o semestre, con todos os cambios documentados aqu칤.

# Clases presenciais

::: column-screen-inset-right
|           Sem치n            | Data        | T칩pico                                                                                                                     |                             Preparaci칩n                             |                                   Presentaci칩ns                                   |                                                       EA                                                        |                                                                                                   Laboratorio                                                                                                   |                                                                                       Traballo individual                                                                                       |                            Avaliaci칩n                            |                                                                                                                                                                                                                                                                                                                       Proxecto                                                                                                                                                                                                                                                                                                                        |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](/weeks/week-1.html)  | M칠r, 4 Out | Lab 0 - Benvida + Presentaci칩n                                                                                                |                                                                 |      [游둰勇끃(/slides/lab-0.html "Lab slides"){aria-label="Lab 0 slides"}      |          |          |          |          |          |
|                           | Xov, Xan 6  | Welcome to STA 210!                                                                                                       |  [游닀](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [游둰勇끃(/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [游늶](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"}       |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [2](/weeks/week-2.html)  | Lun, Xan 10 | Lab 1 - Meet the toolkit                                                                                                  |                                                                 |      [游둰勇끃(/slides/lab-1.html "Lab slides"){aria-label="Lab 1 slides"}      |                                                                                                                 |                                                               [游눹](/labs/lab-1.html "Lab instructions"){aria-label="Lab 1 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Mar, Xan 11 | Simple linear regression (SLR)                                                                                            |  [游닀](/weeks/week-2.html#prepare){aria-label="Week 2 summary"}  |  [游둰勇끃(/slides/lec-2.html "Lecture slides"){aria-label="Lecture 2 slides"}  |                                                                                                                 |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Xov, Xan 13 | SLR: Model fitting in R with tidymodels                                                                                   |                                                                 |  [游둰勇끃(/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}  |    [游늶](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"}     |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Ven, Xan 14 | Released: HW 5                                                                                                            |                                                                 |                                                                            |                                                                                                                 |                                                                                                                                                                                                         |                                                              [九꽲잺](/hw/hw-5.html){aria-label="HW 5 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |             | Due: Lab 1                                                                                                                |                                                                 |                                                                            |                                                                                                                 | [游눹](/labs/lab-1.html "Lab instructions"){aria-label="Lab 1 instructions"} [游딓勇끃(https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-1-key.pdf){aria-label="Lab 1 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [3](/weeks/week-3.html)  |          |          |          |          |          |          |          |          |          |

:::


