---
title: "Descrición do Proxecto da Asignatura"
---

## Timeline

[Ideas para o proxecto](#topic-ideas) due Fri, Feb 18

[Propota de proxecto](#project-proposal) due Fri, Mar 18

[Borrador de informe](#draft-report) due Fri, Apr 8

[Informe Final](#written-report) due Mon, Apr 25

[Presentación en vídeo + slides](#video-presentation--slides) Thu, Apr 28

## Introdución

**O Proxecto**: Pensa en unha idea ou concepto da Enxeñaría Química e desenvólvea en forma de demostración, utilidade, simulación ou programa de cálculo ou deseño. Ese é o verdadeiro obxecivo. Trátase de que uses a simulación ou a optimización para ilustar de algún xeito algúns dos aspectos mais importantes da enxeñaría química.

O modelo no que te basees xa pode existir, ou ben, podes plantexar un por ti mesmo sobre algún tema que che insterse especialmente, ou buscalo na web. O teu obxectivo ca realización do proxecto debe de ser a demostraci´on das túas competencias adquiridas na materia en forma de un caso práctico xa sexa de deseño, solución, mellora ou simple simulación demostrativa.

A linguaxe de programación no é tan importante coma a idea. Non obstante a simulación debe presentar ó usuario unha interface (ou GUI) que o faga útil (por exemplo formularios de excel, widgets de python, GUI's de Matlab, etc.).

Todos os traballos deben estar acompañados da súa documentación, tanto do obxectivo, método, algortimo, código e interface, así comop un emmplod e aplicación xa terminado.

Antes de pasar á realización do mesmo deberás entregar (entregable en MOOVI) un preproxecto quye deberá ser aprobado polo teu profesor, En caso de que a túa proposta non sexa axeitada ou non cunpla cun nivel acorde ca asignatura, non poderás empezar e debesrás reescribir a túa proposta, ben sexa sonbre o mesmo tema ou sobre outro.

### Loxística

Traballarás no proxecto de xeito indicidual.

Os entregables obligatorios para o proxecto final son

- Un **Informe escrito** e reproducible que detalla a súa análise, os algoritmos ou métodos numéricos usados, o diagrama de fluxo da programación d a descrición da interface.
- Un **Código executable** debvidamente documentado acorde ó documento anterior.
- Unha **Presentación en formato slides**
- Un **Vídeo explicativo do proxcto e a súas funcionalidads**

## Ideas para o proxecto {#topic-ideas}

#### Introdución e propósito

- Indique a fonte e o propósito da simulacion.
- Describe a fonte(s) de inspiración e a utilidade que lle ves.
- Describe as observacións e as características para plantexala e desenvolvela.

#### Pregunta de utilidade

- Describe para uqé se podería utilizar a túa simulació e os potenciais usuarios da mesma.

## Proposta de proxeto {#project-proposal}

O propósito da proposta do proxecto é axudarche a pensar na túa estratexia de análise cedo.

Inclúe o seguinte na proposta:

### Sección 1 - Introdución

A sección de introdución inclúe

- Unha introdución ao tema que estás simulando.
- A motivación para a da túa elección (citando calquera bibliografía relevante).
- A pregunta ou problema xeral que desexas resolver.
- As túas hipóteses sobre a cuestión.
 
### Sección 2 - Descrición dos datos

Nesta sección, describirás o conxunto de datos que vas usar. Isto inclúe

- Descrición das observacións no conxunto de datos, variables, librerías etc.,
- Descrición de como se procederá orixinalmente á realización da simulación, a interface e os usuarios ña que vai dirixida.
 
### Sección 3 - Enfoque da análise

Nesta sección, proporcionarás unha breve visión xeral do teu enfoque de análise da simulación. Isto inclúe:

- Descrición da variables de resposta.
- Estatísticas de visualización gráfica e nmérica das variable de resposta.
- Lista de variables que vas a consideradar na simulación.
- Técnica de modelado numérico (regresión lineal múltiple, ODE,etc.).

### Dicionario de datos (enunciado de variables principais)

- Inclúe un dicionario de datos para todas as variables do conxunto de datos da simulación.
- Crea un ficheiro "Readme" do teu proxecto en texto plano no cartafol principal.

### Envío

Mete todos os teus ficheiros finais nda proposta e entrégaos nun ficheiro zip, ou creao un repositorio ou disco compartido (por exemplo GitHub ou OneDrive) e envía o PDF da súa proposta ca ligazón ó repositorio.

### Cualficación das propostas

|Total |10 ptos |
| ---------------------- | -------- |
| Introdución |3 ptos |
| Descrición dos datos |2 ptos |
| Enfoque da análise |4 ptos |
| Dicionario de datos |1 pts |

Cada compoñente cualificarase do seguinte xeito:

- Cumpre as expectativas (crédito completo): Todos os elementos necesarios están completados e son precisos. A narración está escrita con claridade, todas as táboas e visualizacións están ben formatadas e o traballo sería presenta nun look profesional.

- Cerca das expectativas (crédito medio): Hai algúns elementos que faltan e/ou imprecisos. Hai algúns problemas co formato.

- Non cumpre as expectativas (sen crédito): Faltan os elementos principais. O traballo non está perfectamente formateado e non presentaría nun look profesional.

## Borrador de informe {#Draft-Report}

O propósito do borrador é darche a oportunidade de obter comentarios anticipados sobre a túa simulación. Polo tanto, o borrador e centraranse principalmente nunha análise exploratoria da simulación, modelado de datos e interpretacións iniciais do obxectivo.

Escribe o borrador no ficheiro **escrito-informe** no repo do seu proxecto ou engrégao en **MOOVI**.

A continuación móstrase unha breve descrición das seccións para centrarse no borrador:

### Introdución e datos

Esta sección inclúe unha introdución á motivación da simulación, datos implicado e obxecto d mesma. Describe os datos e definicións de variables clave. Tamén debe incluír algunha análise exploratorios do proceso.

### Metodoloxía

Esta sección inclúe unha breve descrición do seu proceso de modelado. Explica o razoamento do tipo de modelo que estás encaixando, as variables de predición consideradas para o modelo incluíndo calquera interacción. Ademais, mostra como chegas ós requeriments finais que lle pos á túa simulación, describindo o proceso de selección de modelos, calquera transformacións variables (se é necesario) e calquera outra consideración relevante que formaron parte ds mesma.

Explica tamén a linguaxe de programacion que vas a usa e cáles son as rzóns da túa elección.

### Resultados

Nesta sección, presenta os resultados que se poidan tirar da simulción e inclúe unha breve discusión sobre os aspectos mais relevantes que ti considreres.

Esta sección tamén inclúe interpretacións iniciais e conclusións extraídas do modelo así como a interfaces que vas a presentar ó usuario.

## Informe escrito {#escrito-informe}

O seu informe escrito debe completarse no ficheiro `escrito-informe.qmd` e debe ser reproducible.
Todos os membros do equipo deberían contribuír ao repositorio de GitHub, con compromisos significativos regulares.

Antes de finalizar a súa escritura, asegúrese de que a impresión de anacos de código está desactivada coa opción `eco = false`.

** Enviarás o PDF do teu informe final sobre o graduado. **

O PDF que envíe debe coincidir cos ficheiros do seu repositorio GitHub *exactamente *.
Os compoñentes obrigatorios do informe están a continuación.
Vostede é libre de engadir seccións adicionais segundo sexa necesario.
O informe, incluídas as visualizacións, debería ser ** non máis de 10 páxinas de longo. ** Non é un requisito mínimo de páxina;Non obstante, debes abordar de xeito exhaustivo toda a análise e informe.

Sexa selectivo no que inclúe na súa redacción final.
O obxectivo é escribir unha narración cohesionada que demostre unha análise completa e completa en vez de explicar cada paso da análise.

Benvido a incluír un apéndice con traballo adicional ao final do documento de informe escrito;Non obstante, a clasificación basearase en gran medida no contido do corpo principal do informe.
Debe asumir que o lector non verá o material do apéndice a menos que o solicite no corpo principal do informe.
O apéndice debe estar formateado e fácil para o lector para navegar.
Non está incluído no límite de 10 páxinas.

O informe escrito vale 40 puntos, descomprimido do seguinte xeito:

|Total |100 ptos |
| ------------------------------- | -------- |
| Introdución | 10 ptos  |
| Metodoloxía | 25 ptos |
| Resultados  | 15 pts  |
| Discusión + Descrición + Conclusións | 20 ptos |
| Organización + Formato + Interface | 20 ptos |

[Click here](/documents/project-report-rubric.pdf "Project rubric") for a PDF of the written report rubric.

### Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

#### Grading criteria

The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research.
The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.
The data cleaning process is cleaarly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The explanatory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables.
It incorporates appropriate visualizations and summary statistics.

### Methodology

This section includes a brief description of your modeling process.
Explain the reasoning for the type of model you're fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, interactions considered, variable transformations (if needed), assessment of conditions and diagnostics, and any other relevant considerations that were part of the model fitting process.

#### Grading criteria

The analysis steps are appropriate for the data and research question.
The group used a thorough and careful approach to select the final model; the approach is clearly described in the report.
The model selection process took into account potential interaction effects and addressed any violations in model conditions.
The model conditions and diagnostics are thoroughly and accurately assessed for their model.
If violations of model conditions are still present, there was a reasonable attempt to address the violations based on the course content.

### Results

This is where you will output the final model with any relevant model fit statistics.

Describe the key results from the model.
The goal is not to interpret every single variable in the model but rather to show that you are proficient in using the model output to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.

#### Grading criteria

The model fit is clearly assessed, and interesting findings from the model are clearly described.
Interpretations of model coefficients are used to support the key findings and conclusions, rather than merely listing the interpretation of every model coefficient.
If the primary modeling objective is prediction, the model's predictive power is thoroughly assessed.

### Discussion + Conclusion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, this section will include ideas for future work.

#### Grading criteria

Overall conclusions from analysis are clearly described, and the model results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis, and ideas for future work are clearly described.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

#### Grading criteria

The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

## Video presentation + slides

### Slides

In addition to the written report, your team will also create presentation slides and record a video presentation that summarize and showcase your project.
Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions.
These slides should serve as a brief visual addition to your written report and will be graded for content and quality.

**For submission, convert these slides to a .pdf document, and submit the PDF of the slides on Gradescope.**

The slide deck should have no more than 6 content slides + 1 title slide.
Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format for the 6 slides.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Introduce the data
-   Slide 3: Highlights from EDA
-   Slide 4: Final model
-   Slide 5: Interesting findings from the model
-   Slide 6: Conclusions + future work

### Video presentation

For the video presentation, you can speak over your slide deck, similar to the lecture content videos.
**The video presentation must be no longer than 8 minutes.** It is fine if the video is shorter than 8 minutes, but it cannot exceed 8 minutes.
You may use can use any platform that works best for your group to record your presentation.
Below are a few resources on recording videos:

-   [Recording presentations in Zoom](https://kb.siue.edu/61721)
-   [Apple Quicktime for screen recording](https://support.apple.com/en-gb/guide/quicktime-player/qtp97b08e666/mac)
-   [Windows 10 built-in screen recording functionality](https://www.youtube.com/watch?v=OfPbr1mRDuo)
-   [Kap for screen recording](https://getkap.co/)

Once your video is ready, upload the video to Warpwire, then embed the video in an new discussion post on Conversations.

#### To upload your video to Warpwire:

-   Click the Warpwire tab in the course Sakai site.
-   Click the "+" and select "Upload files".
-   Locate the video on your computer and click to upload.
-   Once you've uploaded the video to Warpwire, click to share the video and copy the video's URL. You will need this when you post the video in the discussion forum.

#### To post the video to the discussion forum

-   Click the Presentations tab in the course Sakai site.
-   Click the Presentations topic.
-   Click "Start a new conversation".
-   Make the title "Your Team Name: Project Title". For example, "Teaching Team: Our Awesome Presentation".
-   Click the Warpwire icon (between the table and shopping cart icons).
-   Select your video, then click "Insert 1 item." This will embed your video in the conversation.
-   Under the video, paste the URL to your video.
-   You're done!

## Presentation comments {#presentation-comments}

Each student will be assigned 2 presentations to watch.
Your viewing assignments will be posted later in the semester.

Watch the group's video, then click "Reply" to post a question for the group.
You may not post a question that's already been asked on the discussion thread.
Additionally, the question should be (i) substantive (i.e. it shouldn't be "Why did you use a bar plot instead of a pie chart"?), (ii) demonstrate your understanding of the content from the course, and (iii) relevant to that group's specific presentation, i.e demonstrating that you've watched the presentation.

*This portion of the project will be assessed individually.*

## Reproducibility + organization

All written work (with exception of presentation slides) should be reproducible, and the GitHub repo should be neatly organized.

The GitHub repo should have the following structure:

-   `README`: Short project description and data dictionary

-   `written-report.qmd` & `written-report.pdf`: Final written report

-   `/data`: Folder that contains the data set for the final project.

-   `/previous-work`: Folder that contains the `topic-ideas` and `project-proposal` files.

-   `/presentation`: Folder with the presentation slides.

    -   If your presentation slides are online, you can put a link to the slides in a `README.md` file in the `presentation` folder.

Points for reproducibility + organization will be based on the reproducibility of the written report and the organization of the project GitHub repo.
The repo should be neatly organized as described above, there should be no extraneous files, all text in the README should be easily readable.

## Peer teamwork evaluation

You will be asked to fill out a survey where you rate the contribution and teamwork of each team member by assigning a contribution percentage for each team member.
Filling out the survey is a prerequisite for getting credit on the team member evaluation.
If you are suggesting that an individual did less than half the expected contribution given your team size (e.g., for a team of four students, if a student contributed less than 12.5% of the total effort), please provide some explanation.
If any individual gets an average peer score indicating that this was the case, their grade will be assessed accordingly.

If you have concerns with the teamwork and/or contribution from any team members, please email me by the project video deadline.
**You only need to email me if you have concerns**.
Otherwise, I will assume everyone on the team equally contributed and will receive full credit for the teamwork portion of the grade.

## Overall grading

The grade breakdown is as follows:

| Total                              | 100 pts |
|------------------------------------|---------|
| **Topic ideas**                    | 5 pts   |
| **Project proposal**               | 10 pts  |
| **Peer review**                    | 10 pts  |
| **Written report**                 | 40 pts  |
| **Slides + video presentation**    | 20 pts  |
| **Reproducibility + organization** | 5 pts   |
| **Video comments**                 | 5 pts   |
| **Peer teamwork evaluation**       | 5 pts   |

*Note: No late project reports or videos are accepted.*

### Grading summary

Grading of the project will take into account the following:

-   Content - What is the quality of research and/or policy question and relevancy of data to those questions?
-   Correctness - Are statistical procedures carried out and explained correctly?
-   Writing and Presentation - What is the quality of the statistical presentation, writing, and explanations?
-   Creativity and Critical Thought - Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

A general breakdown of scoring is as follows:

-   *90%-100%*: Outstanding effort. Student understands how to apply all statistical concepts, can put the results into a cogent argument, can identify weaknesses in the argument, and can clearly communicate the results to others.
-   *80%-89%*: Good effort. Student understands most of the concepts, puts together an adequate argument, identifies some weaknesses of their argument, and communicates most results clearly to others.
-   *70%-79%*: Passing effort. Student has misunderstanding of concepts in several areas, has some trouble putting results together in a cogent argument, and communication of results is sometimes unclear.
-   *60%-69%*: Struggling effort. Student is making some effort, but has misunderstanding of many concepts and is unable to put together a cogent argument. Communication of results is unclear.
-   *Below 60%*: Student is not making a sufficient effort.

### Late work policy

**There is no late work accepted on this project.** Be sure to turn in your work early to avoid any technological mishaps.
